const notes=["C","C♯","D","D♯","E","F","F♯","G","G♯","A","A♯","B"];
const patterns={
  major:{label:"Major",steps:[0,2,4,5,7,9,11],formula:"W · W · H · W · W · W · H"},
  natural:{label:"Natural minor",steps:[0,2,3,5,7,8,10],formula:"W · H · W · W · H · W · W"},
  harmonic:{label:"Harmonic minor",steps:[0,2,3,5,7,8,11],formula:"1 · 2 · ♭3 · 4 · 5 · ♭6 · 7"},
  melodic:{label:"Melodic minor (ascending)",steps:[0,2,3,5,7,9,11],formula:"1 · 2 · ♭3 · 4 · 5 · 6 · 7"}
};
const intervals=[
  ["Perfect unison",0,"P1"],["Minor 2nd",1,"m2"],["Major 2nd",2,"M2"],["Minor 3rd",3,"m3"],
  ["Major 3rd",4,"M3"],["Perfect 4th",5,"P4"],["Tritone",6,"TT"],["Perfect 5th",7,"P5"],
  ["Minor 6th",8,"m6"],["Major 6th",9,"M6"],["Minor 7th",10,"m7"],["Major 7th",11,"M7"],["Octave",12,"P8"]
];
const qualities={
  major:{label:"Major triad",steps:[0,4,7],formula:"1 · 3 · 5"},
  minor:{label:"Minor triad",steps:[0,3,7],formula:"1 · ♭3 · 5"},
  diminished:{label:"Diminished triad",steps:[0,3,6],formula:"1 · ♭3 · ♭5"},
  augmented:{label:"Augmented triad",steps:[0,4,8],formula:"1 · 3 · ♯5"},
  dominant7:{label:"Dominant 7th",steps:[0,4,7,10],formula:"1 · 3 · 5 · ♭7"},
  major7:{label:"Major 7th",steps:[0,4,7,11],formula:"1 · 3 · 5 · 7"},
  minor7:{label:"Minor 7th",steps:[0,3,7,10],formula:"1 · ♭3 · 5 · ♭7"}
};
const lessons=[
  {id:"notation",number:"01",group:"Foundations",title:"Music notation",summary:"Understand the grand staff, Middle C, note anatomy, rhythmic grouping, and how standard notation connects to guitar tablature.",points:["The grand staff joins the treble and bass staves. Middle C sits between them on its own short ledger line.","A note’s vertical position shows pitch. Each step moves to the next line or space, while ledger lines extend the readable range.","A written note can contain a notehead, stem, and flag. Beams group flagged notes, and a triplet fits three equal notes into the usual space of two.","Guitar music can align a five-line notation staff with six-line tablature: notation shows pitch and rhythm, while tab shows string and fret."],lab:"notation"},
  {id:"octaves",number:"02",group:"Foundations",title:"Octaves & the pitch map",summary:"Follow repeated note names across registers and understand why an octave sounds like the same pitch at a new height.",points:["Western notation repeats the letter names A through G.","Moving twelve semitones reaches the same note name one octave higher or lower.","Guitar strings and frets contain several playable locations for the same pitch."],lab:"octave"},
  {id:"rhythm",number:"03",group:"Rhythm",title:"Notes, rests & dots",summary:"Compare note values, matching rest values, dotted notes, and triplets.",points:["A dot adds half of a note’s original duration.","A rest marks measured silence.","A triplet fits three equal notes into the time normally occupied by two."],lab:"rhythm"},
  {id:"meter",number:"04",group:"Rhythm",title:"Time signatures & meters",summary:"Explore simple, compound, and odd meters as repeating beat structures.",points:["The top number counts beats or subdivisions in each bar.","Simple meter divides each beat into two; compound meter divides it into three.","Odd meters combine groups such as 2 + 2 + 3."],lab:"rhythm"},
  {id:"chromatic",number:"05",group:"Scales",title:"Chromatic, diatonic & modes",summary:"Start with all twelve pitches, then select seven-note scales and their seven modal starting points.",points:["The chromatic scale uses all twelve pitches, one semitone apart.","A diatonic scale contains seven notes arranged as five whole steps and two half steps.","The seven modes rotate the diatonic pattern around a different tonal centre."],lab:"scale"},
  {id:"major",number:"06",group:"Scales",title:"Major scale",summary:"Build the familiar seven-note major sound from its whole-step and half-step pattern.",points:["The major pattern is W–W–H–W–W–W–H.","Each letter name should appear once when a scale is spelled traditionally.","Scale degree 7 is the leading tone, one semitone below the tonic."],lab:"scale"},
  {id:"minor",number:"07",group:"Scales",title:"Minor scales",summary:"Compare natural, harmonic, and melodic minor formulas from the same tonic.",points:["Natural minor lowers 3, 6, and 7 from the parallel major scale.","Harmonic minor raises degree 7 from natural minor.","Ascending melodic minor raises degrees 6 and 7."],lab:"scale"},
  {id:"scale-degrees",number:"08",group:"Scales",title:"Scale degrees & key relationships",summary:"Name each scale position and connect relative and parallel major and minor keys.",points:["Scale degrees are numbered 1–7 and also have names such as tonic, dominant, and leading tone.","Relative major and minor share a key signature; relative minor begins on degree 6 of major.","Parallel major and minor share a tonic but use different scale notes."],lab:"degrees"},
  {id:"intervals",number:"09",group:"Harmony",title:"Intervals",summary:"Measure the distance between two notes and learn the names used to describe it.",points:["Intervals combine a number with a quality such as major, minor, or perfect.","A perfect fifth spans seven semitones.","An octave returns to the same note name twelve semitones higher."],lab:"interval"},
  {id:"sound",number:"10",group:"Harmony",title:"Harmonic series & consonance",summary:"See how overtones shape timbre and why some pitch combinations feel stable or tense.",points:["A vibrating string produces a fundamental plus quieter whole-number overtones.","Simple frequency relationships such as 2:1 and 3:2 tend to sound strongly blended.","Consonance and dissonance are musical colours: tension becomes meaningful through context and resolution."],lab:"harmonics"},
  {id:"chords",number:"11",group:"Harmony",title:"Triads & seventh chords",summary:"Stack scale tones to build major, minor, diminished, augmented, and seventh chords.",points:["A basic triad contains root, third, and fifth.","Changing the third or fifth changes the chord quality.","A seventh chord adds another stacked third above the triad."],lab:"chord"},
  {id:"diatonic-chords",number:"12",group:"Harmony",title:"Diatonic chords & symbols",summary:"Build a chord on every scale degree and read the symbols musicians use to describe them.",points:["Major-key triads follow I–ii–iii–IV–V–vi–vii°.","Uppercase Roman numerals indicate major quality; lowercase indicates minor.","Chord symbols communicate root and quality without fixing a single voicing."],lab:"diatonic"},
  {id:"guitar-map",number:"13",group:"Guitar",title:"Guitar map",summary:"Learn the notation for strings, frets, open notes, and fretting-hand fingers.",points:["Strings are numbered 6 to 1 from the lowest-pitched E to the highest-pitched E; standard tuning is E–A–D–G–B–E.","Fret 0 means an open string. Each higher fret raises the pitch by one semitone, and fret 12 repeats the open note one octave higher.","Fretting-hand fingers are T for thumb, then 1 index, 2 middle, 3 ring, and 4 little finger."],lab:"fretboard"},
  {id:"caged",number:"14",group:"Guitar",title:"CAGED & open chord formulas",summary:"Compare the course’s CAGED major and AED minor open-shape families by fingering and chord degree.",points:["The major family uses C, A, G, E, and D shapes; every voicing rearranges the same chord tones 1–3–5.","The practical minor family uses A, E, and D shapes and lowers the third: 1–♭3–5.","Recognising the root inside each shape makes it easier to move and connect the shapes across the neck."],lab:"caged"},
  {id:"barre",number:"15",group:"Guitar",title:"Fretboard notes & barre chords",summary:"Use roots on the sixth and fifth strings to move E-, Em-, A-, and Am-shaped chords.",points:["The sixth-string root names movable E and Em shapes.","The fifth-string root names movable A and Am shapes.","A barre acts like a movable nut, preserving the shape at a new fret."],lab:"barre"},
  {id:"seventh-shapes",number:"16",group:"Guitar",title:"Seventh chord shapes",summary:"Compare practical major 7, minor 7, and dominant 7 guitar shapes.",points:["Major 7 uses 1–3–5–7.","Minor 7 uses 1–♭3–5–♭7.","Dominant 7 uses 1–3–5–♭7 and strongly points toward resolution."],lab:"sevenths"},
  {id:"guitar-harmonics",number:"17",group:"Guitar",title:"Natural guitar harmonics",summary:"Relate the 12th-, 7th-, and 5th-fret nodes to the string fractions and partials shown in the course.",points:["A natural harmonic appears where a vibrating string divides into equal sections.","The 12th fret divides the string in half, the 7th into thirds, and the 5th into quarters.","Touch lightly above the fret wire without pressing, pluck the string, then release the touching finger."],lab:"string-harmonics"},
  {id:"progressions",number:"18",group:"Guitar",title:"Chord progressions & strumming",summary:"Turn scale harmony into playable progressions and organise rhythm into repeatable strumming patterns.",points:["A progression is a sequence of chord functions, often written with Roman numerals.","I–V–vi–IV and ii–V–I can be moved to any key.","Keep the strumming hand moving evenly, even when a stroke is silent."],lab:"progression"}
];
const references=[
  {kind:"Your course",title:"Music Theory and Guitar Lessons",description:"The original Canva course that inspired this theory notebook.",url:"https://www.canva.com/design/DAEf7zWMAi4/Zj_7lRY3fK6kh8gt6EDrUQ/edit"},
  {kind:"Guided lessons",title:"musictheory.net Lessons",description:"Free animated lessons covering notation, rhythm, scales, intervals, chords, and harmony.",url:"https://www.musictheory.net/lessons"},
  {kind:"Practice",title:"musictheory.net Exercises",description:"Interactive note, fretboard, interval, scale, chord, and ear-training exercises.",url:"https://www.musictheory.net/exercises"},
  {kind:"Open textbook",title:"Open Music Theory",description:"A deeper open-source textbook for fundamentals, harmony, form, and analysis.",url:"https://openmusictheory.github.io/"},
  {kind:"Guitar application",title:"Fender Theory Guides",description:"Guitar-focused articles that connect scales, chords, rhythm, and ear training to playing.",url:"https://www.fender.com/articles/tags/theory"},
  {kind:"Guitar handbook",title:"Berklee Online Guitar Handbook",description:"A practical guitar reference from Berklee Online.",url:"https://assets.online.berklee.edu/handbooks/berklee-online-guitar-handbook.pdf"}
];

const options=list=>list.map((item,index)=>`<option value="${index}">${item}</option>`).join("");
const lessonCard=lesson=>`<button class="theory-card" data-lesson="${lesson.id}" data-search="${lesson.group} ${lesson.title} ${lesson.summary}"><span class="theory-number">${lesson.number}</span><span class="eyebrow">${lesson.group}</span><strong>${lesson.title}</strong><small>${lesson.summary}</small><span class="theory-card-action">Open lesson →</span></button>`;
const notationLab=()=>`<span class="eyebrow">Interactive notation guide</span><h2>Read the musical picture</h2><div class="notation-tabs" role="tablist" aria-label="Notation figures"><button data-notation-view="grand" role="tab" aria-selected="true">Grand staff</button><button data-notation-view="anatomy" role="tab" aria-selected="false">Note anatomy</button><button data-notation-view="guitar" role="tab" aria-selected="false">Guitar & tab</button></div>
<figure class="notation-figure" data-notation-panel="grand"><svg viewBox="0 0 760 320" role="img" aria-labelledby="grand-title grand-desc"><title id="grand-title">Grand staff and Middle C</title><desc id="grand-desc">Treble and bass staves joined together with notes moving through Middle C.</desc><g class="staff-lines">${[62,78,94,110,126,194,210,226,242,258].map(y=>`<line x1="76" y1="${y}" x2="706" y2="${y}"/>`).join("")}</g><path class="staff-brace" d="M58 62 C30 62 44 126 24 148 C44 170 30 258 58 258"/><text class="clef treble" x="79" y="124">𝄞</text><text class="clef bass" x="80" y="245">𝄢</text><line class="ledger middle-ledger" x1="360" y1="160" x2="400" y2="160"/><g class="pitch-notes"><ellipse cx="135" cy="242" rx="10" ry="7"/><ellipse cx="185" cy="226" rx="10" ry="7"/><ellipse cx="235" cy="210" rx="10" ry="7"/><ellipse cx="285" cy="194" rx="10" ry="7"/><ellipse class="middle-note" cx="380" cy="160" rx="11" ry="7"/><ellipse cx="475" cy="126" rx="10" ry="7"/><ellipse cx="525" cy="110" rx="10" ry="7"/><ellipse cx="575" cy="94" rx="10" ry="7"/><ellipse cx="625" cy="78" rx="10" ry="7"/></g><g class="pitch-labels"><text x="128" y="276">F</text><text x="178" y="276">A</text><text x="228" y="276">C</text><text x="278" y="276">E</text><text class="middle-label" x="348" y="33">Middle C</text><path class="middle-arrow" d="M380 42 L380 139 M374 130 L380 139 L386 130"/><text x="468" y="52">C</text><text x="518" y="52">E</text><text x="568" y="52">G</text><text x="618" y="52">B</text></g><text class="figure-caption" x="380" y="304" text-anchor="middle">Bass staff ← lower pitches · Middle C · higher pitches → Treble staff</text></svg><figcaption><strong>Grand staff</strong><span>Middle C bridges the bass and treble staves on a ledger line.</span></figcaption></figure>
<figure class="notation-figure" data-notation-panel="anatomy" hidden><svg viewBox="0 0 760 320" role="img" aria-labelledby="anatomy-title anatomy-desc"><title id="anatomy-title">Parts of a musical note and rhythmic grouping</title><desc id="anatomy-desc">A labelled notehead, stem and flag, beamed notes, and a triplet.</desc><g class="note-anatomy"><ellipse class="note-head" cx="150" cy="212" rx="30" ry="20"/><line class="note-stem" x1="178" y1="210" x2="178" y2="83"/><path class="note-flag" d="M178 84 C240 102 232 152 187 168 C214 135 207 116 178 110"/><path class="label-line" d="M107 225 L54 250"/><text x="14" y="269">Notehead</text><path class="label-line" d="M179 102 L119 55"/><text x="48" y="48">Stem</text><path class="label-line" d="M207 119 L262 78"/><text x="269" y="80">Flag</text></g><g class="beam-example"><ellipse cx="365" cy="213" rx="22" ry="15"/><ellipse cx="465" cy="213" rx="22" ry="15"/><line x1="386" y1="210" x2="386" y2="112"/><line x1="486" y1="210" x2="486" y2="112"/><line class="beam" x1="386" y1="112" x2="486" y2="112"/><text x="415" y="86">Beam</text></g><g class="triplet-example"><ellipse cx="570" cy="213" rx="17" ry="11"/><ellipse cx="625" cy="213" rx="17" ry="11"/><ellipse cx="680" cy="213" rx="17" ry="11"/><line x1="586" y1="210" x2="586" y2="132"/><line x1="641" y1="210" x2="641" y2="132"/><line x1="696" y1="210" x2="696" y2="132"/><line class="beam" x1="586" y1="132" x2="696" y2="132"/><path class="triplet-bracket" d="M582 104 L582 92 L700 92 L700 104"/><text class="triplet-number" x="637" y="86">3</text><text x="609" y="260">Triplet</text></g></svg><figcaption><strong>Note anatomy</strong><span>Flags show shorter values; beams group them; the bracketed 3 identifies a triplet.</span></figcaption></figure>
<figure class="notation-figure" data-notation-panel="guitar" hidden><svg viewBox="0 0 760 340" role="img" aria-labelledby="guitar-title guitar-desc"><title id="guitar-title">Standard guitar staff aligned with tablature</title><desc id="guitar-desc">Five standard notation lines above six tablature lines with corresponding notes and fret numbers.</desc><g class="staff-lines">${[55,71,87,103,119].map(y=>`<line x1="82" y1="${y}" x2="704" y2="${y}"/>`).join("")}${[202,222,242,262,282,302].map(y=>`<line x1="82" y1="${y}" x2="704" y2="${y}"/>`).join("")}</g><text class="clef treble" x="84" y="116">𝄞</text><text class="tab-mark" x="91" y="263">TAB</text><g class="bar-lines"><line x1="82" y1="55" x2="82" y2="119"/><line x1="704" y1="55" x2="704" y2="119"/><line x1="82" y1="202" x2="82" y2="302"/><line x1="704" y1="202" x2="704" y2="302"/></g><g class="guitar-notes"><ellipse cx="210" cy="119" rx="10" ry="7"/><ellipse cx="315" cy="103" rx="10" ry="7"/><ellipse cx="420" cy="87" rx="10" ry="7"/><ellipse cx="525" cy="71" rx="10" ry="7"/><g class="chord-stack"><ellipse cx="630" cy="119" rx="10" ry="7"/><ellipse cx="630" cy="103" rx="10" ry="7"/><ellipse cx="630" cy="87" rx="10" ry="7"/><ellipse cx="630" cy="71" rx="10" ry="7"/></g></g><g class="tab-numbers"><text x="202" y="308">8</text><text x="307" y="288">7</text><text x="412" y="268">5</text><text x="517" y="248">5</text><text x="622" y="308">8</text><text x="622" y="288">7</text><text x="622" y="268">5</text><text x="622" y="248">5</text></g><g class="alignment-guides"><line x1="210" y1="135" x2="210" y2="188"/><line x1="315" y1="119" x2="315" y2="188"/><line x1="420" y1="103" x2="420" y2="188"/><line x1="525" y1="87" x2="525" y2="188"/><line x1="630" y1="135" x2="630" y2="188"/></g><text class="figure-caption" x="393" y="330" text-anchor="middle">The same musical events shown as pitch and rhythm above, string and fret below.</text></svg><figcaption><strong>Guitar staff and tablature</strong><span>Read vertically: each tab number lines up with its standard-notation note.</span></figcaption></figure>`;

const chordDiagram=(name,frets,degrees)=>{
  const values=frets.split("");
  return `<figure class="chord-diagram"><figcaption><strong>${name}</strong><span>${frets}</span></figcaption><svg viewBox="0 0 140 150" role="img" aria-label="${name} guitar chord, ${frets}"><g class="chord-grid">${[20,40,60,80,100,120].map(x=>`<line x1="${x}" y1="28" x2="${x}" y2="122"/>`).join("")}${[28,51.5,75,98.5,122].map((y,index)=>`<line class="${index===0?"nut":""}" x1="20" y1="${y}" x2="120" y2="${y}"/>`).join("")}</g>${values.map((value,index)=>{const x=20+(index*20);if(value==="x")return`<text class="chord-open" x="${x}" y="18">×</text>`;if(value==="0")return`<circle class="chord-open-ring" cx="${x}" cy="13" r="5"/>`;const fret=Number(value);return`<circle class="chord-dot" cx="${x}" cy="${39.75+((fret-1)*23.5)}" r="7"/>`}).join("")}</svg><small>${degrees}</small></figure>`;
};
const chordSet=(items)=>`<div class="chord-diagram-grid">${items.map(item=>chordDiagram(...item)).join("")}</div>`;
const theoryTabs=(labels,panels)=>`<div class="guitar-tabs" role="tablist">${labels.map((label,index)=>`<button type="button" data-guitar-tab="${index}" aria-selected="${index===0}">${label}</button>`).join("")}</div>${panels.map((panel,index)=>`<section class="guitar-tab-panel" data-guitar-panel="${index}" ${index===0?"":"hidden"}>${panel}</section>`).join("")}`;

export function theoryPage(main,escape){
  main.classList.remove("theory-lesson-open");
  main.innerHTML=`<section class="theory-hero"><div><span class="eyebrow">Music theory · guitar lessons</span><h1>See the pattern.<br>Hear the music.</h1><p class="lead">Move from notation to harmony, then bring each idea onto the guitar through an edited learning path based on your course.</p></div><div class="theory-orbit" aria-label="Twelve chromatic notes">${notes.map((note,index)=>`<span style="--i:${index}">${note}</span>`).join("")}<strong>12<br><small>tones</small></strong></div></section>
  <div class="theory-path" aria-label="Suggested learning path"><span><b>01</b> Foundations</span><i>→</i><span><b>02</b> Rhythm</span><i>→</i><span><b>03</b> Scales</span><i>→</i><span><b>04</b> Harmony</span><i>→</i><span><b>05</b> Guitar</span></div>
  <section class="theory-shell"><aside class="theory-sidebar"><label class="theory-search">Find a lesson<input id="theory-search" type="search" placeholder="Scales, rhythm, chords…"></label><nav aria-label="Theory topics">${[...new Set(lessons.map(x=>x.group))].map(group=>`<a href="#/theory" data-theory-section="theory-${group.toLowerCase()}">${group}</a>`).join("")}<a href="#/theory" data-theory-section="theory-references">References</a></nav></aside>
  <div><div id="theory-lessons" class="theory-grid">${[...new Set(lessons.map(x=>x.group))].map(group=>`<section id="theory-${group.toLowerCase()}" class="theory-group"><div class="card-top"><h2>${group}</h2><span>${lessons.filter(x=>x.group===group).length} lessons</span></div><div class="theory-card-grid">${lessons.filter(x=>x.group===group).map(lessonCard).join("")}</div></section>`).join("")}<section id="theory-references" class="theory-resources"><div><span class="eyebrow">References & further study</span><h2>Go deeper with trusted sources.</h2><p>These materials informed and extend the lessons in this notebook.</p></div><div class="resource-grid">${references.map(item=>`<a class="resource-card" href="${item.url}" target="_blank" rel="noopener"><span>${item.kind}</span><strong>${item.title}</strong><small>${item.description}</small><b>Visit resource ↗</b></a>`).join("")}</div></section></div>
  <section id="theory-workspace" class="theory-workspace" hidden></section></div></section>`;
  const workspace=main.querySelector("#theory-workspace"),lessonList=main.querySelector("#theory-lessons");
  const showTheoryIndex=(sectionId,{focusSearch=false}={})=>{
    main.classList.remove("theory-lesson-open");
    workspace.hidden=true;
    lessonList.hidden=false;
    history.replaceState(null,"","#/theory");
    window.requestAnimationFrame(()=>window.requestAnimationFrame(()=>{
      if(sectionId)main.querySelector(`#${sectionId}`)?.scrollIntoView({behavior:"smooth",block:"start"});
      else main.scrollIntoView({behavior:"smooth",block:"start"});
      if(focusSearch)main.querySelector("#theory-search").focus({preventScroll:true});
    }));
  };
  main.querySelectorAll("[data-theory-section]").forEach(link=>link.onclick=event=>{event.preventDefault();showTheoryIndex(link.dataset.theorySection)});
  main.querySelector("#theory-search").oninput=event=>{const query=event.target.value.trim().toLowerCase();main.querySelectorAll(".theory-card").forEach(card=>card.hidden=query&&!card.dataset.search.toLowerCase().includes(query));main.querySelectorAll(".theory-group").forEach(group=>group.hidden=!group.querySelector(".theory-card:not([hidden])"))};
  const noteName=(root,step)=>notes[(root+step)%12];
  const drawScale=()=>{const root=Number(workspace.querySelector("#scale-root").value),pattern=patterns[workspace.querySelector("#scale-pattern").value];workspace.querySelector("#scale-result").innerHTML=pattern.steps.concat(12).map((step,index)=>`<span><small>${index===7?1:index+1}</small>${noteName(root,step)}</span>`).join("");workspace.querySelector("#scale-formula").textContent=pattern.formula};
  const drawInterval=()=>{const root=Number(workspace.querySelector("#interval-root").value),interval=intervals[Number(workspace.querySelector("#interval-size").value)];workspace.querySelector("#interval-result").innerHTML=`<span>${notes[root]}</span><b>+ ${interval[1]} semitone${interval[1]===1?"":"s"}</b><span>${noteName(root,interval[1])}</span>`;workspace.querySelector("#interval-name").textContent=`${interval[0]} · ${interval[2]}`};
  const drawChord=()=>{const root=Number(workspace.querySelector("#chord-root").value),quality=qualities[workspace.querySelector("#chord-quality").value];workspace.querySelector("#chord-result").innerHTML=quality.steps.map((step,index)=>`<span><small>${quality.formula.split(" · ")[index]}</small>${noteName(root,step)}</span>`).join("");workspace.querySelector("#chord-name").textContent=`${notes[root]} ${quality.label}`};
  const openLesson=(id,{preservePager=false}={})=>{const oldPager=workspace.querySelector(".lesson-pager"),oldPagerTop=preservePager&&oldPager?oldPager.getBoundingClientRect().top:null,lessonIndex=lessons.findIndex(item=>item.id===id),lesson=lessons[lessonIndex],previous=lessons[lessonIndex-1],next=lessons[lessonIndex+1];main.classList.add("theory-lesson-open");lessonList.hidden=true;workspace.hidden=false;workspace.innerHTML=`<button id="all-lessons" class="back">← All theory lessons</button><div class="theory-lesson-head"><div><span class="eyebrow">${lesson.group} · Lesson ${lesson.number}</span><h1>${escape(lesson.title)}</h1><p class="lead">${escape(lesson.summary)}</p></div></div><div class="theory-lesson-grid"><article class="panel"><h2>Core ideas</h2><ol class="theory-points">${lesson.points.map(point=>`<li>${escape(point)}</li>`).join("")}</ol></article><article class="theory-lab panel"></article></div><nav class="lesson-pager" aria-label="Lesson navigation"><button id="previous-lesson" ${previous?"":"disabled"}><span>← Previous lesson</span><strong>${previous?escape(previous.title):"This is the first lesson"}</strong></button><button id="next-lesson" ${next?"":"disabled"}><span>Next lesson →</span><strong>${next?escape(next.title):"Course complete"}</strong></button></nav>`;
    const lab=workspace.querySelector(".theory-lab");
    if(lesson.lab==="scale"){lab.innerHTML=`<span class="eyebrow">Scale lab</span><h2>Build a scale</h2><div class="lab-controls"><label>Root<select id="scale-root">${options(notes)}</select></label><label>Scale<select id="scale-pattern">${Object.entries(patterns).map(([key,item])=>`<option value="${key}">${item.label}</option>`).join("")}</select></label></div><div id="scale-result" class="note-output"></div><p id="scale-formula" class="formula"></p>`;lab.querySelectorAll("select").forEach(select=>select.onchange=drawScale);drawScale()}
    else if(lesson.lab==="interval"){lab.innerHTML=`<span class="eyebrow">Interval lab</span><h2>Measure two notes</h2><div class="lab-controls"><label>Starting note<select id="interval-root">${options(notes)}</select></label><label>Distance<select id="interval-size">${intervals.map((item,index)=>`<option value="${index}">${item[0]}</option>`).join("")}</select></label></div><div id="interval-result" class="interval-output"></div><p id="interval-name" class="formula"></p>`;lab.querySelectorAll("select").forEach(select=>select.onchange=drawInterval);drawInterval()}
    else if(lesson.lab==="chord"){lab.innerHTML=`<span class="eyebrow">Chord lab</span><h2>Build a chord</h2><div class="lab-controls"><label>Root<select id="chord-root">${options(notes)}</select></label><label>Quality<select id="chord-quality">${Object.entries(qualities).map(([key,item])=>`<option value="${key}">${item.label}</option>`).join("")}</select></label></div><div id="chord-result" class="note-output"></div><p id="chord-name" class="formula"></p>`;lab.querySelectorAll("select").forEach(select=>select.onchange=drawChord);drawChord()}
    else if(lesson.lab==="rhythm")lab.innerHTML=`<span class="eyebrow">Beat visualiser</span><h2>Feel the grouping</h2><div class="meter-demo"><button data-meter="4">4 / 4</button><button data-meter="6">6 / 8</button><button data-meter="7">7 / 8</button></div><div id="beat-row" class="beat-row"></div><p class="formula">Choose a meter to see its beat grouping.</p>`;
    else if(lesson.lab==="octave")lab.innerHTML=`<span class="eyebrow">Pitch map</span><h2>Same name, new register</h2><div class="octave-map">${["C2","C3","C4","C5"].map((note,index)=>`<span style="--octave:${index}"><small>${index===2?"Middle C":"octave"}</small>${note}</span>`).join("<i>12 semitones</i>")}</div><p class="formula">Each step doubles the frequency while preserving the note identity.</p>`;
    else if(lesson.lab==="degrees")lab.innerHTML=`<span class="eyebrow">Degree map</span><h2>Jobs inside a key</h2><div class="degree-map">${["Tonic","Supertonic","Mediant","Subdominant","Dominant","Submediant","Leading tone"].map((name,index)=>`<span><b>${index+1}</b><small>${name}</small></span>`).join("")}</div><p class="formula">1 feels like home · 5 creates motion · 7 leans toward 1</p>`;
    else if(lesson.lab==="harmonics")lab.innerHTML=`<span class="eyebrow">Sound lab</span><h2>One note contains many</h2><div class="harmonic-series">${[1,2,3,4,5,6].map((partial,index)=>`<span style="--partial:${partial}"><i></i><b>${partial}</b><small>${["Fundamental","Octave","Perfect 5th","2 octaves","Major 3rd","Perfect 5th"][index]}</small></span>`).join("")}</div><div class="tension-scale"><span>more blended</span><i></i><span>more tense</span></div><p class="formula">Overtone labels show the interval reduced into the nearest octave.</p>`;
    else if(lesson.lab==="diatonic")lab.innerHTML=`<span class="eyebrow">Harmony map</span><h2>Chords in a major key</h2><div class="diatonic-row">${[["I","major","home"],["ii","minor","pre-dominant"],["iii","minor","colour"],["IV","major","departure"],["V","major","tension"],["vi","minor","relative minor"],["vii°","diminished","leading-tone"]].map(item=>`<span><b>${item[0]}</b><small>${item[1]}</small><em>${item[2]}</em></span>`).join("")}</div><p class="formula">Tonic → departure → dominant tension → tonic</p>`;
    else if(lesson.lab==="fretboard")lab.innerHTML=`<span class="eyebrow">Guitar notation guide</span><h2>Strings, frets & fingers</h2><div class="guitar-legend"><span><b>6 → 1</b><small>lowest to highest string</small></span><span><b>E A D G B E</b><small>standard open tuning</small></span><span><b>0</b><small>open string</small></span></div><div class="fretboard-scroll"><div class="fretboard-map named"><div class="fret-labels"><i>string</i><i>open</i>${[1,2,3,4,5,6,7,8,9,10,11,12].map(fret=>`<i>${fret}</i>`).join("")}</div>${["1 · e","2 · B","3 · G","4 · D","5 · A","6 · E"].map((string,stringIndex)=>`<div class="fret-string"><b>${string}</b><em>${string.split(" · ")[1]}</em>${Array.from({length:12},(_,fret)=>`<span class="${[2,4,6,8,11].includes(fret)?"marker":""}${fret===11&&stringIndex===3?" double":""}"></span>`).join("")}</div>`).join("")}</div></div><div class="finger-key">${[["T","thumb"],["1","index"],["2","middle"],["3","ring"],["4","little"]].map(([number,name])=>`<span><b>${number}</b><small>${name}</small></span>`).join("")}</div><p class="formula">Fret numbers count away from the nut; the 12th fret repeats every open note one octave higher.</p>`;
    else if(lesson.lab==="caged")lab.innerHTML=`<span class="eyebrow">Open-shape reference</span><h2>CAGED major · AED minor</h2>${theoryTabs(["Major · CAGED","Minor · AED"],[`${chordSet([["C","x32010","3 · 1 · 3 · 5 · 1"],["A","x02220","5 · 1 · 5 · 1 · 3 · 5"],["G","320003","1 · 3 · 5 · 1 · 3 · 1"],["E","022100","1 · 5 · 1 · 3 · 5 · 1"],["D","xx0232","5 · 1 · 5 · 1 · 3"]])}<p class="formula">Every major shape contains 1 · 3 · 5.</p>`,`${chordSet([["Am","x02210","5 · 1 · 5 · 1 · ♭3 · 5"],["Em","022000","1 · 5 · 1 · ♭3 · 5 · 1"],["Dm","xx0231","5 · 1 · 5 · 1 · ♭3"]])}<p class="formula">Minor lowers the third: 1 · ♭3 · 5.</p>`])}`;
    else if(lesson.lab==="barre")lab.innerHTML=`<span class="eyebrow">Movable-shape map</span><h2>Root note names the chord</h2>${theoryTabs(["6th-string roots","5th-string roots"],[`${`<div class="root-strip">${["E","F","F♯","G","G♯","A","A♯","B","C","C♯","D","D♯","E"].map((note,fret)=>`<span><small>${fret}</small><b>${note}</b></span>`).join("")}</div>`}<div class="barre-examples"><span><small>Major family</small><b>E → F → F♯ → G</b><em>E shape · 1–3–5</em></span><span><small>Minor family</small><b>Em → Fm → F♯m → Gm</b><em>Em shape · 1–♭3–5</em></span></div>`,`${`<div class="root-strip">${["A","A♯","B","C","C♯","D","D♯","E","F","F♯","G","G♯","A"].map((note,fret)=>`<span><small>${fret}</small><b>${note}</b></span>`).join("")}</div>`}<div class="barre-examples"><span><small>Major family</small><b>A → A♯ → B → C</b><em>A shape · 1–3–5</em></span><span><small>Minor family</small><b>Am → A♯m → Bm → Cm</b><em>Am shape · 1–♭3–5</em></span></div>`])}<p class="formula">Choose a root fret, barre it like a movable nut, then keep the E- or A-family shape.</p>`;
    else if(lesson.lab==="sevenths")lab.innerHTML=`<span class="eyebrow">Common open voicings</span><h2>Major 7 · minor 7 · dominant 7</h2>${theoryTabs(["Major 7 · CAGD","Minor 7 · AED","Dominant 7 · CAGED + B"],[`${chordSet([["Cmaj7","x32000","1 · 3 · 5 · 7"],["Amaj7","x02120","1 · 3 · 5 · 7"],["Gmaj7","320002","1 · 3 · 5 · 7"],["Dmaj7","xx0222","1 · 3 · 5 · 7"]])}`,`${chordSet([["Am7","x02010","1 · ♭3 · 5 · ♭7"],["Em7","020000","1 · ♭3 · 5 · ♭7"],["Dm7","xx0211","1 · ♭3 · 5 · ♭7"]])}`,`${chordSet([["C7","x32310","1 · 3 · 5 · ♭7"],["A7","x02020","1 · 3 · 5 · ♭7"],["G7","320001","1 · 3 · 5 · ♭7"],["E7","020100","1 · 3 · 5 · ♭7"],["D7","xx0212","1 · 3 · 5 · ♭7"],["B7","x21202","1 · 3 · 5 · ♭7"]])}`])}`;
    else if(lesson.lab==="string-harmonics")lab.innerHTML=`<span class="eyebrow">Natural harmonic map</span><h2>Divide one string into equal parts</h2><div class="harmonic-string-map"><div class="string-node"><span class="nut">nut</span><i class="node node-5"><b>5th</b></i><i class="node node-7"><b>7th</b></i><i class="node node-12"><b>12th</b></i><span class="bridge">bridge</span></div><div class="harmonic-fractions"><span><b>12th fret</b><i>½ string</i><small>2nd partial · octave</small></span><span><b>7th fret</b><i>⅓ string</i><small>3rd partial · octave + fifth</small></span><span><b>5th fret</b><i>¼ string</i><small>4th partial · two octaves</small></span></div></div><p class="formula">Touch directly over the fret wire—do not press—pluck, then lift the touching finger.</p>`;
    else if(lesson.lab==="progression"){lab.innerHTML=`<span class="eyebrow">Play-along lab</span><h2>Move a progression</h2><div class="lab-controls"><label>Key<select id="progression-root">${options(notes)}</select></label><label>Progression<select id="progression-pattern"><option value="I:0,V:7,vi:9,IV:5">I · V · vi · IV</option><option value="ii:2,V:7,I:0">ii · V · I</option><option value="I:0,IV:5,V:7,I:0">I · IV · V · I</option></select></label></div><div id="progression-result" class="progression-output"></div><div class="strum-strip"><b>4/4 strum</b><span>↓</span><span>↓</span><span>↑</span><span>↑</span><span>↓</span><span>↑</span></div>`;const drawProgression=()=>{const root=Number(lab.querySelector("#progression-root").value),chords=lab.querySelector("#progression-pattern").value.split(",").map(item=>{const [symbol,step]=item.split(":");return{symbol,step:Number(step)}});lab.querySelector("#progression-result").innerHTML=chords.map(chord=>`<span><small>${chord.symbol}</small>${noteName(root,chord.step)}${chord.symbol===chord.symbol.toLowerCase()?"m":""}</span>`).join("")};lab.querySelectorAll("select").forEach(select=>select.onchange=drawProgression);drawProgression()}
    else if(lesson.id==="notation"){lab.innerHTML=notationLab();const notationTabs=lab.querySelectorAll("[data-notation-view]");notationTabs.forEach(button=>button.onclick=()=>{notationTabs.forEach(tab=>tab.setAttribute("aria-selected",String(tab===button)));lab.querySelectorAll("[data-notation-panel]").forEach(panel=>panel.hidden=panel.dataset.notationPanel!==button.dataset.notationView)})}
    else lab.innerHTML=`<span class="eyebrow">Guitar reading map</span><h2>Staff meets fretboard</h2><div class="tab-demo"><span>e ─── 0 ─── 3 ───</span><span>B ─── 1 ─── 0 ───</span><span>G ─── 0 ─── 0 ───</span><span>D ─── 2 ─── 0 ───</span><span>A ─── 3 ─── 2 ───</span><span>E ──────── 3 ───</span></div><p class="formula">Numbers are frets; lines are strings.</p>`;
    const guitarTabs=lab.querySelectorAll("[data-guitar-tab]");
    guitarTabs.forEach(button=>button.onclick=()=>{guitarTabs.forEach(tab=>tab.setAttribute("aria-selected",String(tab===button)));lab.querySelectorAll("[data-guitar-panel]").forEach(panel=>panel.hidden=panel.dataset.guitarPanel!==button.dataset.guitarTab)});
    lab.querySelectorAll("[data-meter]").forEach(button=>button.onclick=()=>{const meter=Number(button.dataset.meter),groups=meter===6?[3,3]:meter===7?[2,2,3]:[1,1,1,1];lab.querySelector("#beat-row").innerHTML=groups.map((size,index)=>`<span>${Array.from({length:size},(_,beat)=>`<i class="${beat===0?"accent":""}">${groups.slice(0,index).reduce((a,b)=>a+b,0)+beat+1}</i>`).join("")}</span>`).join("")});
    workspace.querySelector("#all-lessons").onclick=()=>showTheoryIndex(null,{focusSearch:true});
    if(previous)workspace.querySelector("#previous-lesson").onclick=()=>openLesson(previous.id,{preservePager:true});
    if(next)workspace.querySelector("#next-lesson").onclick=()=>openLesson(next.id,{preservePager:true});
    const lessonHash=`#/theory/${id}`;if(preservePager){history.replaceState(null,"",lessonHash);const newPagerTop=workspace.querySelector(".lesson-pager").getBoundingClientRect().top;if(oldPagerTop!=null)window.scrollBy(0,newPagerTop-oldPagerTop)}else{if(location.hash!==lessonHash)location.hash=lessonHash;workspace.scrollIntoView({behavior:"smooth",block:"start"})}
  };
  main.querySelectorAll("[data-lesson]").forEach(button=>button.onclick=()=>openLesson(button.dataset.lesson));
  const requested=location.hash.split("/")[2];if(requested&&lessons.some(lesson=>lesson.id===requested))openLesson(requested)
}
